name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      DISPLAY: ":99.0" # Set a display for Xvfb

    services:
      xvfb:
        image: selenium/standalone-chrome:latest
        options: -e VNC_SERVER=true -e VNC_PORT=5900

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'  
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b
      with :
        gradle-version: '8.10'

    - uses: pmd/pmd-github-actions@v2
      with:
        version: '6.55.0'
        rulesets: ’java-basic’

    - name: Fail build if there are violations
      if: steps.pmd.outputs.violations > 3
      run: exit 1

    - name: Start Xvfb
      run: Xvfb $DISPLAY -ac -screen 0 1600x1200x24 > /dev/null 2>&1 &

    - name: Build with Gradle 8.10
      run: gradle build

    - name: Publish a test report
      uses: actions/upload-artifact@v4
      with:
        path: app/build/reports/tests
        
