name: Code Scanning Alerts with PMD

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'  
        distribution: 'temurin'

    - uses: pmd/pmd-github-actions@v2
      with:
        version: '6.55.0'
        rulesets: ’java-basic’

    - name: Fail build if there are violations
      if: steps.pmd.outputs.violations > 3
      run: exit 1
        
