name: PMD

on: [push, pull_request]

permissions:
  contents: read

jobs:
  pmd-code-scan:
  
    permissions:
      contents: read
      security-events: write
      actions: read
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - uses: pmd/pmd-github-action@v2
      id: pmd
      with:
        version: '6.55.0'
        sourcePath: 'src/main/java'
        rulesets: 'java-basic'
        
    - name: Fail build if there are violations
      if: steps.pmd.outputs.violations != 0
      run: exit 1
